apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-service
  name: myapp-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp-yaml
  type: NodePort
status:
  loadBalancer: {}
